### ISSUE TITLE
Image never appears

### ISSUE THREAD

**Issue by aniketroxx** [sanjaypra555/Facebook-Profile-Pic-Filter#2]
![imagneverappears](https://cloud.githubusercontent.com/assets/6142430/20235941/ebcc179a-a8c8-11e6-980b-8a7c2a5049c1.PNG)

Nothing appears in here . I am not getting what's wrong . I just added app id and set filter src.

```
	function getDp(id){
                document.getElementById('btn').innerHTML = '';
		document.getElementById('status').innerHTML = 'Please wait......';
		imageSrc = "https://graph.facebook.com/"+id+"/picture?width=600&height=600";
		filterSource = "logo.png";
		setFacebookFilter(filterSource,imageSrc);

	}
```

**Comment by Surendrajat** [comment]
@aniketroxx I can think of only two possibilities here:
1. **logo.png** isn't the right path of your **filterSource** or
2. you're using some browser that doesn't support HTML5 Canvas (less likely).
Please make sure you check your uploaded image has name **logo.png** and its in same directory with **index.html** file.
You can also check [this test preview](http://fb1.pe.hu/).

**Comment by aniketroxx** [comment]
Its not fetching Profile picture . FB application ID is right too . Test preview you sent fetches profile picture .

**Comment by Surendrajat** [comment]
@aniketroxx  Everything seems to be working fine as you are able to log into app. Just recheck filter source path. Try changing filter image url to an external image link.  You can print profile pic only if you're not sure.
The [index.html](https://github.com/sanjaypra555/Facebook-Profile-Pic-Filter/blob/master/index.html) file is updated and is easier to troubleshoot at which point its not responding. You can use your browser console for this job.
Also I've [updated test preview](http://fb0.pe.hu/) of the same.
